package com.mendes.scheduling_platform.password;
import com.mendes.scheduling_platform.exception.BusinessException; import com.mendes.scheduling_platform.platform.PlatformAdminRepository; import com.mendes.scheduling_platform.user.User; import com.mendes.scheduling_platform.user.UserRepository;
import org.springframework.beans.factory.annotation.Value; import org.springframework.mail.SimpleMailMessage; import org.springframework.mail.javamail.JavaMailSender; import org.springframework.scheduling.annotation.Scheduled; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.security.SecureRandom; import java.time.*; import java.util.Base64;
@Service
public class PasswordResetService {
 private final UserRepository users; private final PlatformAdminRepository admins; private final PasswordResetTokenRepository tokens; private final PasswordEncoder encoder; private final JavaMailSender mail; private final String frontendUrl; private final SecureRandom random=new SecureRandom();
 public PasswordResetService(UserRepository u,PlatformAdminRepository a,PasswordResetTokenRepository t,PasswordEncoder e,JavaMailSender m,@Value("${app.frontend-url:${APP_FRONTEND_URL:http://localhost:5173}}") String frontendUrl){users=u;admins=a;tokens=t;encoder=e;mail=m;this.frontendUrl=frontendUrl;}
 @Transactional public void requestUser(String email){users.findFirstByEmailIgnoreCase(email).ifPresent(u->{String raw=create(u.getId(),null);send(email,frontendUrl+"/reset-password?token="+raw);});}
 @Transactional public void requestPlatform(String email){admins.findByEmailIgnoreCase(email).ifPresent(a->{String raw=create(null,a.getId());send(email,frontendUrl+"/platform/reset-password?token="+raw);});}
 @Transactional public void reset(String raw,String password){if(raw==null||raw.length()<20)throw new BusinessException("Token inválido");var t=tokens.findByTokenHash(hash(raw)).orElseThrow(()->new BusinessException("Token inválido ou expirado"));if(t.getUsedAt()!=null||t.getExpiresAt().isBefore(Instant.now()))throw new BusinessException("Token inválido ou expirado");if(t.getUserId()!=null){var u=users.findById(t.getUserId()).orElseThrow(()->new BusinessException("Usuário não encontrado"));u.setPassword(encoder.encode(password));users.save(u);}else{var a=admins.findById(t.getPlatformAdminId()).orElseThrow(()->new BusinessException("Administrador não encontrado"));a.setPassword(encoder.encode(password));admins.save(a);}t.setUsedAt(Instant.now());tokens.save(t);}
 private String create(Long userId,Long adminId){String raw=randomToken();var t=new PasswordResetToken();t.setUserId(userId);t.setPlatformAdminId(adminId);t.setTokenHash(hash(raw));t.setExpiresAt(Instant.now().plusHours(1));tokens.save(t);return raw;}
 private void send(String email,String link){SimpleMailMessage m=new SimpleMailMessage();m.setTo(email);m.setSubject("AgendaHub — recuperação de senha");m.setText("Use este link para redefinir sua senha (válido por 1 hora):
"+link);try{mail.send(m);}catch(Exception ignored){}}
 private String randomToken(){byte[] b=new byte[32];random.nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);}
 private String hash(String raw){try{return java.util.HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(raw.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 @Scheduled(cron="0 15 * * * *") public void cleanup(){tokens.deleteAllByExpiresAtBefore(Instant.now());}
}
